language: node_js
node_js:
  - "v11.11.0"
env:
  - NODE_ENV=production
before_deploy:
  - "npm run pre-deploy"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: develop
before_script:
  - "npm i -g gatsby"
  - "npm i"
  - "echo GITHUB_TOKEN=$GITHUB_TOKEN > .env.production"
script:
  - "npm run build"
branches:
  except:
  - master
